version: '3.8'
services:
  testing_db:
    image: postgres
    container_name: project2test
    ports:
      - 5433:5432
    volumes:
      # persist data of container  
      - test_db:/var/lib/postgresql/data
      # when starting the container, have a look in the database folder & use the SQL file to seed database
      - ./database/:/docker-entrypoint-initdb.d/:ro
    environment:
      - POSTGRES_DB=council_app
      - POSTGRES_USER=testing
      - POSTGRES_PASSWORD=jkljkl

volumes:
  test_db: